//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Locação = new HashSet<Locação>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public string Notificação { get; set; }
    
        public virtual ICollection<Locação> Locação { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual Endereço Endereço { get; set; }
    }
}
