//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DadosContainer : DbContext
    {
        public DadosContainer()
            : base("name=DadosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Veículo> VeículoSet { get; set; }
        public DbSet<Histórico> HistóricoSet { get; set; }
        public DbSet<Relatório> RelatórioSet { get; set; }
        public DbSet<Modelo> ModeloSet { get; set; }
        public DbSet<Funcionário> FuncionárioSet { get; set; }
        public DbSet<Locação> LocaçãoSet { get; set; }
        public DbSet<Reserva> ReservaSet { get; set; }
        public DbSet<Manutenção> ManutençãoSet { get; set; }
        public DbSet<Cliente> ClienteSet { get; set; }
        public DbSet<Endereço> EndereçoSet { get; set; }
    }
}
