//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
=======
>>>>>>> origin/Code_Generator_fix
    public partial class Endereço
    {
        public int Id { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Rua { get; set; }
        public int Número { get; set; }
        public int CEP { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
