//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
=======
>>>>>>> origin/Code_Generator_fix
    public partial class Funcionário
    {
        public Funcionário()
        {
            this.Relatório = new HashSet<Relatório>();
            this.Veículo = new HashSet<Veículo>();
            this.Manutenção = new HashSet<Manutenção>();
            this.Reserva = new HashSet<Reserva>();
            this.Locação = new HashSet<Locação>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CarteiraDeTrabalho { get; set; }
        public double Salário { get; set; }
        public string Função { get; set; }
    
        public virtual ICollection<Relatório> Relatório { get; set; }
        public virtual ICollection<Veículo> Veículo { get; set; }
        public virtual ICollection<Manutenção> Manutenção { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Locação> Locação { get; set; }
    }
}
