//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Histórico
    {
        public Histórico()
        {
            this.Manutenção = new HashSet<Manutenção>();
            this.Locação = new HashSet<Locação>();
        }
    
        public int Id { get; set; }
    
        public virtual Veículo Veículo { get; set; }
        public virtual Relatório Relatório { get; set; }
        public virtual ICollection<Manutenção> Manutenção { get; set; }
        public virtual ICollection<Locação> Locação { get; set; }
    }
}
