//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
=======
>>>>>>> origin/Code_Generator_fix
    public partial class Manutenção
    {
        public int Id { get; set; }
        public string Inicio { get; set; }
        public string Fim { get; set; }
        public string Motivo { get; set; }
    
        public virtual Histórico Histórico { get; set; }
        public virtual Funcionário Funcionário { get; set; }
    }
}
