//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Veículo = new HashSet<Veículo>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Fornecedor { get; set; }
    
        public virtual ICollection<Veículo> Veículo { get; set; }
    }
}
