//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Veículo = new HashSet<Veículo>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Fornecedor { get; set; }
    
        public virtual ICollection<Veículo> Veículo { get; set; }
=======
    public partial class Modelo
    {
        //private string p;
       // private string p_2;

        public Modelo() {}

        public Modelo(string nome, string fornecedor)
        {
            this.Nome = nome;
            this.Fornecedor = fornecedor;
        }

       /* public Modelo(string p, string p_2)
        {
            // TODO: Complete member initialization
            this.p = p;
            this.p_2 = p_2;
        }*/

        //Métodos responsáveis pela interação com o BD
        public void gravar()
        {
            using (var ctx = new DadosContainer())
            {
                ctx.AddToModeloSet(this);
                ctx.SaveChanges();
            }
        }

        public static Modelo pesquisar()
        {
            using (var ctx = new DadosContainer())
            {
                foreach (var x in ctx.ModeloSet)
                {
                    Console.WriteLine(x);
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Modelo " + this.Nome + " com fornecedor " + this.Fornecedor;
        }
>>>>>>> origin/Code_Generator_fix
    }
}
