//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBR_Rent_a_car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veículo
    {
        public Veículo()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Cor { get; set; }
        public int Ano { get; set; }
        public string Categoria { get; set; }
        public int Quilometragem { get; set; }
        public byte Estado { get; set; }
    
        public virtual Histórico Histórico { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Funcionário Funcionário { get; set; }
    }
}
